config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  get "new-home" => "new_home#index"
  get "about_us" => "about_us#index"
  get "clients" => "clients#index"
  get "products/:permalink" => "products#index", :as => "products"
  get "products/:name/:permalink" => "products#show", :as => "product"
  get "contact_us" => "contact_us#new", :as => "contact_us"
  # post "contact_us" => "contact_us#create", :as => "contact_us"
  get "news" => "news#index", :as => "news"
  get "news/:id" => "news#show", :as => "show_news"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  resources :sessions, :only => [:create]


  get 'tentang-kompor-induksi' => 'home#kompor_induksi', as: "kompor_induksi"
  post "contact_us" => "home#contact_us", as: "save_contact_us"

  get "admin" => "admin/dashboard#index", :as => "admin"
  post "admin/dashboard/change_password"

 namespace :admin do
    resources :banners
    resources :clients
    resources :features
    resources :news, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :products do
      resources :product_images, :only => [:create, :edit, :update, :destroy] do
        member do
          get 'set_primary'
          get 'set_best_seller'
        end
      end
    end
    resources :categories
    resources :product_images, :only => [:index]
    get "product_images/:id/new_product" => "product_images#new_product", :as => "product_images_new_product"
    post "product_images/:id/create_product" => "product_images#create_product", :as => "product_images_create_product"
    get "settings/:name/edit" => "settings#edit", :as => "edit_setting"
    put "settings/:name" => "settings#update", :as => "update_setting"

    
  end

  root :to => 'home#index'
end

app/models/client.rb
class Client < ActiveRecord::Base
  # attr_accessible :client_image, :name, :best_client
  has_permalink :name, :update => true
  has_attached_file :client_image, :url => "/system/:attachment/:id/:style/:basename.:extension", :styles => { :thumb => "100x100",
                                                 :medium => "200x200" }
  validates_attachment_presence :client_image
  validates :name, :presence => true,
                   :length => {:minimum => 1, :maximum => 254}
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < Admin::ApplicationController
  before_filter :find_client, :only => [:destroy, :edit, :update]

  def index
    @clients = Client.paginate(:page => params[:page], :per_page => 10,
                                         :order => "created_at DESC" )
    @no = params[:page].to_i * 10
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(params[:client])
    if @client.save
      flash[:notice] = "Client successfully created"
      redirect_to admin_clients_path
    else
      flash[:error] = "Client failed to create"
      render :action => "new"
    end
  end

  def edit; end

  def update
    if @client.update_attributes(params[:client])
      flash[:notice] = "Client successfully updated"
      redirect_to admin_clients_path
    else
      flash[:error] = "Client failed to update"
      render :action => "edit"
    end
  end

  def destroy
    flash[:notice] =  @client.destroy ? 'Client was successfully deleted.' :
                                      'Client was falied to delete.'
    redirect_to admin_clients_path
  end

  private
    def find_client
      @client = Client.find_by_id(params[:id])
      if @client.nil?
        flash[:error] = "Cannot find the Client with id '#{params[:id]}'"
        redirect_to admin_clients_path
      end
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def index
    @clients = Client.all
  end
end

app/views/admin/clients/_form.html.erb
<div class="field">
  <div class="input-title left"><%= f.label :name, "Name * :" %></div>
  <div class="input-box left"><%= f.text_field :name %></div>
</div>
<div class="field clear-margin">
  <div class="input-title left"><%= f.label :client_image, "Image * :" %></div>
  <div class="input-box left"><%= f.file_field :client_image %></div>
</div>
<div class="field clear-margin">
  <div class="input-title left">&nbsp;</div>
  <div class="input-box left small-font">
    Input image with size 200x200 (width x height)
  </div>
</div>
<div class="field">
  <div class="input-title left">&nbsp;</div>
  <div class="input-box left"><%= f.check_box :best_client %>Best Seller</div>
</div>

app/views/admin/clients/edit.html.erb
<div class="admin-inner-content">
  <div class="admin-inner-content-title">Edit Client</div>
  <div class="admin-inner-content-info">
    <%= raw msg_flash(flash) %>
    <%= form_for([:admin, @client], :url => admin_client_path,
                  :html => { :multipart => true, :method => :put }) do |f| %>
      <%= f.error_messages %>
      <div class="admin-category-testimonial" style="height: 225px;">
        <%= image_tag @client.client_image.url(:medium) %>
      </div><br /><br />
      <%= render :partial => 'form', :locals => { :f => f} %>
      <div class="field">
        <%= f.submit 'Update Client' %>&nbsp;&nbsp;
        <%= link_to 'Back', admin_clients_path %>
      </div>
    <% end %>
    <div class="clear"></div>
  </div>
</div>

app/views/admin/clients/index.html.erb
<div class="admin-inner-content">
  <div class="admin-inner-content-title">Clients</div>
  <div class="admin-inner-content-info">
    <%= raw msg_flash(flash) %>
    <%= link_to "Add New Clients", new_admin_client_path %><br /><br />
    <div class="admin-row border">
      <div class="no">No</div>
      <div class="image">Image</div>
      <div class="client-name">Name</div>
      <div class="action">&nbsp;</div>
    </div>
    <% @clients.each_with_index do |client, x| %>
      <div class="admin-row with-pic">
        <div class="no"><%= x+1 %></div>
        <div class=" client-image"><%= image_tag client.client_image.url(:thumb) %></div>
        <div class="client-name"><%= client.name %></div>
        <div class="action">
          <%= link_to 'Edit', edit_admin_client_path(client.id) %>&nbsp;|&nbsp;
          <%= link_to 'Delete', admin_client_path(client.id),
                                :confirm => "Are you sure?", :method => :delete %>
        </div>
      </div>
    <% end %>
    <div class="paginate"><%= will_paginate @clients, :link_separator => " | ",
                                 :previous_label => "&laquo; previous",
                                 :next_label => "next &raquo;" %></div>
  </div>
</div>

app/views/admin/clients/new.html.erb
<div class="admin-inner-content">
  <div class="admin-inner-content-title">Clients</div>
  <div class="admin-inner-content-info">
    <%= raw msg_flash(flash) %>
    <%= form_for([:admin, @client], :url => admin_clients_path,
                 :html => { :multipart => true}) do |f| %>
      <%= f.error_messages %>
      <%= render :partial => 'form', :locals => { :f => f} %>
      <div class="field">
        <%= f.submit 'Create Client' %>&nbsp;&nbsp;
        <%= link_to 'Back', admin_clients_path %>
      </div>
    <% end %>
    <div class="clear"></div>
  </div>
</div>