config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  get "new-home" => "new_home#index"
  get "about_us" => "about_us#index"
  get "clients" => "clients#index"
  get "products/:permalink" => "products#index", :as => "products"
  get "products/:name/:permalink" => "products#show", :as => "product"
  get "contact_us" => "contact_us#new", :as => "contact_us"
  # post "contact_us" => "contact_us#create", :as => "contact_us"
  get "news" => "news#index", :as => "news"
  get "news/:id" => "news#show", :as => "show_news"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  resources :sessions, :only => [:create]


  get 'tentang-kompor-induksi' => 'home#kompor_induksi', as: "kompor_induksi"
  post "contact_us" => "home#contact_us", as: "save_contact_us"

  get "admin" => "admin/dashboard#index", :as => "admin"
  post "admin/dashboard/change_password"

 namespace :admin do
    resources :banners
    resources :clients
    resources :features
    resources :news, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :products do
      resources :product_images, :only => [:create, :edit, :update, :destroy] do
        member do
          get 'set_primary'
          get 'set_best_seller'
        end
      end
    end
    resources :categories
    resources :product_images, :only => [:index]
    get "product_images/:id/new_product" => "product_images#new_product", :as => "product_images_new_product"
    post "product_images/:id/create_product" => "product_images#create_product", :as => "product_images_create_product"
    get "settings/:name/edit" => "settings#edit", :as => "edit_setting"
    put "settings/:name" => "settings#update", :as => "update_setting"

    
  end

  root :to => 'home#index'
end

app/controllers/new_home_controller.rb
class NewHomeController < ApplicationController
layout "new-application"

  def index
    @banners = Banner.order("created_at DESC")
    @best_sellers = ProductImage.where("is_best_seller = true").limit(6)
    @best_clients = Client.where("best_client = true").limit(7)
    @latest_news = News.order("created_at DESC").limit(2)
    @red_info = Setting.find_by_id(3)
    @blue_info = Setting.find_by_id(4)
  end
end

app/views/new_home/index.html.erb
<% content_for :javascript_includes do %>
  <%= stylesheet_link_tag "camera" %>
  <%= javascript_include_tag  "old_jquery.min", "jquery.easing.1.3",
                             "camera" %>
<% end %>

<script type="text/javascript">
  jQuery(function(){
    jQuery('#camera_wrap_1').camera({
      thumbnails: false,
      fx : 'mosaicSpiral',
      loader	: 'none',
      navigation	: false,
      height: '340px',
      pagination			: true,
      playPause: false,
      imagePath: "assets"
    });
  });
</script>

<div class="banner">
  <div class="camera_wrap camera_azure_skin" id="camera_wrap_1">
    <% @banners.each do |banner| %>
      <%= raw "<div data-src='#{banner.banner_image.url(:large)}'></div>" %>
    <% end %>-->
  </div><!-- #camera_wrap_1 -->
</div>

<div class="clear"></div>

<div class="description">
  <div class="description-box red">
    <div class="desc-title dark-red"><%= @red_info.name.titleize %></div>
    <div class="desc-content"><%= @red_info.content %></div>
  </div>
  <div class="description-box no-margin blue">
    <div class="desc-title dark-blue"><%= @blue_info.name.titleize %></div>
    <div class="desc-content"><%= @blue_info.content %></div>
  </div>
  <%#*<div class="description-box no-margin green">%>
    <%#*<div class="desc-title dark-green">%>
      <%#*Pensil Sablon%>
    <%#*</div>%>
    <%#*<div class="desc-content">%>
      <%#*Pensil Sablon Pensil Sablon Pensil Sablon Pensil Sablon%>
    <%#*</div>%>
  <%#*</div>%>
</div>

<% unless @latest_news.nil? %>
  <div class="home-news">
    <h4>News</h4>
    <% @latest_news.each_with_index do |news, x| %>
      <% no_m = x == 1 ? 'no-margin' : '' %>
    <div class="home-news-box <%= no_m %>">
        <% if news.news_image.file?  %>
          <div class="home-news-image">
            <%= image_tag news.news_image.url(:thumb) %>
          </div>
        <% end %>
        <div style="position:relative">
          <div class="home-news-title"><%= link_to news.title, show_news_path(news.id) %></div>
          <div class="home-news-date">
            <i>Uploaded at : </i><%= news.updated_at.strftime("%d %B %Y") %>
          </div>
          <div class="home-news-content"><%= raw(short_desc(news.content, 300)) %></div>
          <span style="float:right;margin-top: 10px;">
            <%= link_to "Read more >>", show_news_path(news.id)%>
          </span>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<div class="best-seller">
  <h4>Best Seller</h4>
    <% @best_sellers.each_with_index do |best_seller, x| %>
      <% no_m = (x+1)%3 == 0 ? 'no-margin' : '' %>
      <div class="product-box <%= no_m %>">
        <div class="product-image">
          <%#*<span class="new-label">new</span>%>
          <%#*<span class="sale-label">sale</span>%>
          <%= image_tag best_seller.product_image.url(:medium) %>
        </div>
        <div class="product-info">
          <%#= best_seller.product.name %>
          <%= best_seller.note %>
        </div>
      </div>
    <% end %>
</div>

<div class="our-client">
  <h4>Our Client</h4>
  <% @best_clients.each_with_index do |best_client, z| %>
    <% no_m = 'no-margin' if z == 6 %>
    <div class="logo-box <%= no_m %>">
      <%= image_tag best_client.client_image.url(:thumb) %>
    </div>
  <% end %>
  <div class="see_all_client">
    <%= link_to "See All >>", clients_path %>
  </div>
</div>





































<!--

<%# content_for :javascript_includes do %>
  <%#= javascript_include_tag  "jquery.bxslider" %>
  <%#= stylesheet_link_tag  "jquery.bxslider" %>
<%# end %>

<%#*<div class="inner-content">%>
  <%#*<script type="text/javascript">%>
    <%#*$(document).ready(function(){%>
      <%#*$('.slider').bxSlider({%>
        <%#*slideWidth: 200,%>
        <%#*minSlides: 3,%>
        <%#*maxSlides: 3,%>
        <%#*moveSlides: 1,%>
        <%#*slideMargin: 20,%>
        <%#*pager: false%>
      <%#*});%>
    <%#*});%>
  <%#*</script>%>


  <%#*<div class="slider">%>
    <%# (1..5).each do |x| %>
      <%#*<div class="slide"><%= image_tag "#{x}.jpg" %></div>%>
    <%# end %>
  <%#*</div>%>
  <%#*<div class="news" style="margin-top:20px;border-top:2px solid #8E8778;padding-top:20px;">%>
    <%#*<div class="news-image">%>
      <%#= link_to (image_tag "3.jpg"), show_news_path(1) %>
    <%#*</div>%>
    <%#*<div class="news-content">%>
      <%#*<div class="news-title">%>
        <%#= link_to "Berita baru", show_news_path(1) %>
      <%#*</div>%>
      <%#*<div class="news-date">%>
        <%#*<i>uploaded at : 1 February 2014</i>%>
      <%#*</div>%>
      <%#*<div class="news-short-content">%>
        <%#*Larre Ipsum  is simply dummy text of the printing%>
        <%#*and typesetting industry. Lorem Ipsum has been the%>
        <%#*industry's standard dummy text ever since the 1500s,%>
        <%#*when an unknown printer took a galley of type and scrambled%>
        <%#*it to make a type specimen book. It has survived not only%>
        <%#*five centuries, but also the leap into electronic typesetting%>
        <%#= link_to "Read more >>", show_news_path(1) %>
      <%#*</div>%>
    <%#*</div>%>
  <%#*</div>%>
  <%#*<div class="social-networking">%>
    <%#*<div class="fb">%>
      <%#= link_to (image_tag "facebook_logo.png"), "#" %>
    <%#*</div>%>
    <%#*<div class="twitter">%>
      <%#= link_to (image_tag "twitter_logo.png"), "#" %>
      

    <%#*</div>%>
      <%#= link_to "new_bg_1", "#", :onclick => "change_bg('new_bg_1.jpg')" %>&nbsp;&nbsp;
      <%#= link_to "new_bg_2", "#", :onclick => "change_bg('new_bg_2.jpg')" %>&nbsp;&nbsp;
      <%#= link_to "new_bg_3", "#", :onclick => "change_bg('new_bg_3.jpg')" %>&nbsp;&nbsp;
      <%#= link_to "new_bg_4", "#", :onclick => "change_bg('new_bg_4.jpg')" %>&nbsp;&nbsp;
      <%#= link_to "new_bg_5", "#", :onclick => "change_bg('new_bg_5.jpg')" %>
    <%#*<div class="counter">%>
      <%#*Total Visitor : xxxxx%>
    <%#*</div>%>
  <%#*</div>%>
<%#*</div>%>

  <%#*<script type="text/javascript">%>
      <%#*function change_bg(id){%>
        <%#*$("body").css("background", "url('../assets/"+ id +"')");%>
        <%#*//$("body").style.backgroundImage = 'url(' + id + ')';%>
      <%#*}%>
  <%#*</script>%>
-->