config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  get "new-home" => "new_home#index"
  get "about_us" => "about_us#index"
  get "clients" => "clients#index"
  get "products/:permalink" => "products#index", :as => "products"
  get "products/:name/:permalink" => "products#show", :as => "product"
  get "contact_us" => "contact_us#new", :as => "contact_us"
  # post "contact_us" => "contact_us#create", :as => "contact_us"
  get "news" => "news#index", :as => "news"
  get "news/:id" => "news#show", :as => "show_news"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  resources :sessions, :only => [:create]


  get 'tentang-kompor-induksi' => 'home#kompor_induksi', as: "kompor_induksi"
  post "contact_us" => "home#contact_us", as: "save_contact_us"

  get "admin" => "admin/dashboard#index", :as => "admin"
  post "admin/dashboard/change_password"

 namespace :admin do
    resources :banners
    resources :clients
    resources :features
    resources :news, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :products do
      resources :product_images, :only => [:create, :edit, :update, :destroy] do
        member do
          get 'set_primary'
          get 'set_best_seller'
        end
      end
    end
    resources :categories
    resources :product_images, :only => [:index]
    get "product_images/:id/new_product" => "product_images#new_product", :as => "product_images_new_product"
    post "product_images/:id/create_product" => "product_images#create_product", :as => "product_images_create_product"
    get "settings/:name/edit" => "settings#edit", :as => "edit_setting"
    put "settings/:name" => "settings#update", :as => "update_setting"

    
  end

  root :to => 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :find_category, :only => [:index]
  before_action :find_product, :only => [:show]

  def index
    @web_banners = Banner.order("created_at DESC") #Banner.where("b_type = 'web' or b_type = '' or b_type is null ")
    @mobile_banners = [] #Banner.where("b_type = 'mobile'")

    @contact = ContactUs.new
    @pencil_ids = Category.find_by_permalink('pencil').child_categories.map(&:id)
    @embroidery_ids = Category.find_by_permalink('embroidery').child_categories.map(&:id)
    @pencil_products =  Product.joins(:categories).where("categories.id in (?)", @pencil_ids).limit(3)
    @embroidery_products = Product.joins(:categories).where("categories.id in (?)", @embroidery_ids).limit(3)

    @child_categories =  @category.child_categories
    @products = Product.joins("left join categories_products as cp on cp.product_id = products.id").
      where("cp.category_id in (?)", @child_categories.map(&:id)).uniq

    @clients = Client.all
    # @banners = Banner.order("created_at DESC")
    # @best_sellers = ProductImage.where("is_best_seller = true").limit(6)
    # @best_clients = Client.where("best_client = true").limit(7)
    # @latest_news = News.order("created_at DESC").limit(2)
    # @red_info = Setting.find_by_id(3)
    # @blue_info = Setting.find_by_id(4)
  end
  
  private
    def find_category
      @category = Category.includes(:products).find_by_name('Pencil')
      if @category.nil?
        flash[:error] = "Cannot find the category"
        redirect_to root_path
      end
    end

    def find_product
      @product = Product.find_by_permalink(params[:permalink])
      if @product.nil?
        flash[:error] = "Cannot find the Product"
        redirect_to root_path
      end
    end
end

app/views/home/_modal.html.erb
<!-- Modal -->
<div class="modal fade"  id="shop_modal"  tabindex="-1" role="dialog"
     aria-labelledby="demoModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-md" role="document">
    <div class="modal-content" style="background-image: url('/assets/modal-bg.png');background-size: contain;">
      <div class="container-fluid">
        <button type="button" class="close" data-dismiss="modal"
                aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <div class="row modal-ctn">
          <div class="col-md-12">
            <h2 class="pt-sm-3 mb-4 text-center">Shop<br /><span class="u">Now</span></h2>
          </div>
          <div class="col-md-12 btn-link">
            <%= link_to "SHOPEE", "https://shopee.co.id/elektrigo",class: "btn btn-outline-gray", target: "blank" %>
          </div>
          <div class="col-md-12 btn-link">
            <%= link_to "TOKOPEDIA", "https://www.tokopedia.com/kanahome-id",class: "btn btn-outline-gray", target: "blank" %>
          </div>
          <div class="col-md-12 btn-link last">
            <%= link_to "BLIBLI", "https://www.blibli.com/merchant/kanahome-id/KAD-70005",class: "btn btn-outline-gray", target: "blank" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Modal Ends -->

app/views/home/index.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "owl.carousel" %>
  <%= stylesheet_link_tag  "owl.carousel", "animate", "owl.theme", "lunar" %>
<% end %>

<script>
  jQuery(document).ready(function($) {
    $('.banner, .banner-mobile').owlCarousel({
      animateOut: 'fadeOut',
      animateIn: 'fadeIn',
      loop: true,
      autoplay: true,
      autoplayHoverPause: true,
      items: 1,
      nav : true,
      dotsEach: true,
      autoplaySpeed: 5000,
      navText : ['<span class="fa-stack"><i class="fa fa-circle fa-stack-1x"></i><i class="fa fa-chevron-circle-left fa-stack-1x fa-inverse"></i></span>','<span class="fa-stack"><i class="fa fa-circle fa-stack-1x"></i><i class="fa fa-chevron-circle-right fa-stack-1x fa-inverse"></i></span>']
    });

    $('.clients').owlCarousel({
      loop: true,
      margin: 20,
      nav: true,
      items: 5,
      navText : ['<span class="fa-stack"><i class="fa fa-circle fa-stack-1x"></i><i class="fa fa-chevron-circle-left fa-stack-1x fa-inverse"></i></span>','<span class="fa-stack"><i class="fa fa-circle fa-stack-1x"></i><i class="fa fa-chevron-circle-right fa-stack-1x fa-inverse"></i></span>']
    })
  });
</script>

<!-- header -->
<%# adjust_header = current_user.nil? ? "" : "logged-banner" %>
<section id="home">
  <div class="container banner-container">
    <div class="row no-p-lr">
      <div class="col-12 no-p-lr banner owl-carousel owl-theme d-none d-sm-block d-md-block d-lg-block d-xl-block">
        <% @web_banners.each do |banner| %>
          <div class="item">
            <%# alt = banner.alt.blank? ? banner.image.url() : banner.alt %>
            <%= image_tag banner.banner_image.url(), alt: banner.banner_image.url()  %>
          </div>
        <% end %>
      </div>
      <div class="col-12 no-p-lr banner-mobile owl-carousel owl-theme d-block d-sm-none">
        <% @mobile_banners.each do |banner| %>
          <div class="item">
            <% alt = banner.alt.blank? ? banner.image.file.filename : banner.alt %>
            <%= image_tag banner.image.url, alt: alt  %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section id="produk" class="main-section product-head">
  <div class="container">
    <div class="row our-products">
      <div class="col-12"><h2>PRODUK KAMI</h2></div>
      <div class="col-12 text-center">
        <ul class="sub-menu">
          <li class="ic clicked"><%= link_to "Pencil", "javascript:void(0)", id: "pencil-link" %></li>
          <li class="ct"><%= link_to "Embroidery", "javascript:void(0)", id: "embroidery-link" %></li>
        </ul>
      </div>
    </div>
  </div>
</section>

<section class="products pencil">
  <div class="container">
    <div class="row row-eq-heigh">
      <% @pencil_products.each do |product| %>
        <div class="col-12 col-md-4 mb-4">
          <div class="product">
            <%= image_tag product.image.url('medium'), class: "img-fluid mb-4" %>
            <div class="cat_name"><%= product.try(:categories).map(&:name).join(", ") %></div>
            <div class="p_name"><%= product.name %></div>
            <div class="price">
              <%#= number_to_currency(10000000, unit: 'Rp ', separator: ',', delimiter: '.') %>
            </div>
            <hr />
            <div class="p_spec">
              <%#= raw product.description %>
            </div>
            <hr />
            <div class="p_button">
              <%= link_to "Detail", "#", class: "btn btn-outline-green" %>
              <%= link_to "Beli Sekarang", "javascript:void(0)", class: "btn btn-pink",
                          data: {toggle: "modal", target: "#shop_modal"} %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="col-12 text-center">
        <%= link_to "See All >>", products_path('pencil'), class: "btn btn-white p-lr-25" %>
      </div>
    </div>
  </div>
</section>

<section class="products embroidery" style="display:none">
  <div class="container">
    <div class="row">
      <% @embroidery_products.each do |product| %>
        <div class="col-12 col-md-4 mb-4">
          <div class="product">
            <%= image_tag product.image.url('medium'), class: "img-fluid mb-4" %>
            <div class="cat_name"><%= product.try(:categories).map(&:name).join(", ") %></div>
            <div class="p_name"><%= product.name %></div>
            <div class="price">
              <%#= number_to_currency(10000000, unit: 'Rp ', separator: ',', delimiter: '.') %>
            </div>
            <hr />
            <div class="p_spec">
              <%#= raw product.description %>
            </div>
            <hr />
            <div class="p_button">
              <%= link_to "Detail", "#", class: "btn btn-outline-green" %>
              <%= link_to "Beli Sekarang", "javascript:void(0)", class: "btn btn-pink",
                          data: {toggle: "modal", target: "#shop_modal"} %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="col-12 text-center">
        <%= link_to "See All >>", products_path('embroidery'), class: "btn btn-white p-lr-25" %>
      </div>
    </div>
  </div>
</section>

<section id="klien-kami" class="main-section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 text-center mb-5">
        <%= image_tag "Mengapa-pilih-kompor_induksi.png", class: "img-fluid",
                      alt: "Kanahome, kompor induksi, embroidery" %>
      </div>
    
      <div class="col-md-4 col-6 order-2  order-md-1 left-content">
        <div class="the-box">
          <h1>Lebih Aman</h1>
          <div class="desc">
            Ga ada lagi gas bocor atau masakan gosong karena kelupaan dimatiin.
          </div>
        </div>
        <div class="the-box">
          <h1>Praktis</h1>
          <div class="desc">
            Mudah disimpan, juga mudah dibersihkan, tinggal di-lap saja. Tidak perlu angkat tabung gas lagi.
          </div>
        </div>
        <div class="the-box">
          <h1>Minimalis Inspired</h1>
          <div class="desc">
            Bentuknya modern minimalis, juga hemat ruang.
          </div>
        </div>
      </div>

      <div class="col-md-4 col-12 order-1 order-md-2">
        <%= image_tag "kompor-kanahome.gif", class: "img-fluid mb-5 mx-auto d-block gif-mobile",
                      alt: "Kanahome, kompor induksi, embroidery" %>
      </div>

      <div class="col-md-4 col-6 order-3 right-content">
        <div class="the-box">
          <h1>Masak Lebih Cepat</h1>
          <div class="desc">
            Karena panas yang diterima oleh alat masak lebih merata dan efisien diterima 90% oleh alat masak.
          </div>
        </div>
        <div class="the-box">
          <h1>Fitur Canggih</h1>
          <div class="desc">
            Dilengkapi fitur Child-Lock, Timer, Sensor Panas dan Mode Memasak untuk memudahkan anda.
          </div>
        </div>
        <div class="the-box">
          <h1>Eco-Friendly</h1>
          <div class="desc">
            Tidak ada api dan asap, tidak menghasilkan gas buang yang dapat mengakibatkan polusi.
          </div>
        </div>
      </div>
      <div class="col-12 col-md-8 order-4 text-center mb-5">
        <div class="the-box">
          <h1>Hemat, Harga Ekonomis, Garansi Terjamin</h1>
          <div class="desc">
            Terbukti biaya pemakaian listrik kompor induksi lebih hemat 15% lho! 
            Apalagi kompor induksi KANAhome harganya ekonomis tapi tetap kualitas bagus dan 
            garansi terjamin.<!-- Lihat buktinya! -->
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="klien-kami" class="main-section product-head">
  <div class="container">
    <div class="row our-products">
      <div class="col-12"><h2>KLIEN KAMI</h2></div>
      <div class="col-12 no-p-lr clients owl-carousel owl-theme d-none d-sm-block d-md-block d-lg-block d-xl-block">
        <% @clients.each do |client| %>
          <div class="item">
            <%# alt = banner.alt.blank? ? banner.image.url() : banner.alt %>
            <%= image_tag client.client_image.url("thumb"), alt: client.client_image.url()  %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

<section id="hubungi-kami" class="main-section">
  <div class="container-fluid" style="background-color: #666">
    <div class="row">
      <div class="col-12">
        <h2 class="header">Kontak Kami</h2>
      </div>
    </div>
  </div>
  <div class="container" style="margin-top:50px;">
    <%= render :partial => "shared/flash" %>
    <div class="row">
      <div class="col-12 col-lg-4">
        <div class="row">
          <div class="col-12">
            <div class="ca-info">
              <h2 class="cai-title-2">Kontak Kami</h2>
              <p class="text">&nbsp;</p>
              <ul class="info">
                <li>
                  <span class="icon"><%= fa_icon "map-marker" %></span>
                  <span class="title">Find Us</span>
                  <span class="details">
                    MayFair Building, Lantai 1<br />
                    Jl. Sukajadi No.228, Bandung 40153<br />
                    Jawa Barat, Indonesia
                  </span>
                </li>
                <li>
                  <span class="icon"><%= fa_icon "phone" %></span>
                  <span class="title">Call Us</span>
                  <span class="details">+6222 2027 7424<br />+62 811 2263 767 (Whatsapp Only)</span>
                </li>
                <li>
                  <span class="icon"><%= fa_icon "envelope-o" %></span>
                  <span class="title">Mail Us</span>
                  <span class="details">info@elektrigo.co.id</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-lg-8">
        <div class="ca-form">
          <%# <h2 class="title">We Love to Hear From You</h2>
          <p class="info">Please call or email contact form and we will be happy to assist you.</p> %>
          <div class="cf-msg" style="display: none;"></div>
          <%= simple_form_for @contact, url: save_contact_us_path(anchor: "hubungi-kami"), wrapper: :vertical_form,
                    wrapper_mappings: { check_boxes: :vertical_collection } do |f| %>
            <div class="row">
              <div class="col-12"><%= f.error_notification %></div>
              <div class="col-12">
                <div class="ca-input-box">
                  <%= f.input :name, label_html: { class: 'sr-only' }, placeholder: "Name" %>
                </div>
              </div>
              <div class="col-12">
                <div class="ca-input-box">
                  <%= f.input :email, label_html: { class: 'sr-only' }, placeholder: "Email" %>
                </div>
              </div>
              <div class="col-12">
                <div class="ca-input-box">
                  <%#= f.input :phone, label_html: { class: 'sr-only' }, placeholder: "Phone Number" %>
                </div>
              </div> <!-- col-md-4 -->

              <div class="col-12">
                <div class="ca-input-box">
                  <%#= f.input :subject, label_html: { class: 'sr-only' }, placeholder: "Subject" %>
                </div>
              </div>
              <div class="col-12">
                <div class="ca-input-box">
                  <%#= f.input :content, label_html: { class: 'sr-only' }, placeholder: "Write Message", 
                              as: "text", :input_html => { :rows => 7 } %>
                </div>
              </div> <!-- col-md-8 -->

              <div class="col-md-12 mb-3">
                <span><%#= recaptcha_tags %></span>
              </div> <!-- col-md-12 -->

              <div class="col-md-12">
                <button type="submit" class="btn btn-outline-green">Send Message</button>
              </div> <!-- col-md-12 -->
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<%= render partial: "modal"  %>

<script>
  $(document).ready(function () {
    $("#pencil-link").click(function(){
      $("#pencil-link").parent().addClass('clicked')
      $("#embroidery-link").parent().removeClass('clicked')
      $('.embroidery').fadeOut(300, function() {
        $('.pencil').fadeIn(300)
      });
    })
    $("#embroidery-link").click(function(){
      $("#embroidery-link").parent().addClass('clicked')
      $("#pencil-link").parent().removeClass('clicked')
      $('.pencil').fadeOut(300, function() {
        $('.embroidery').fadeIn(300)
      });
    })


    if(window.location.href.indexOf("#") >= 0){
      anr = "#" + window.location.href.split("#")[1];
      $('html, body').animate({
          scrollTop: $(anr).offset().top - 80
      }, 600);
    }
    $(window).on('scroll', function () {
      mainSection = $('.main-section'),
      mainSectionLength = mainSection.length,
      links = $('#menu li'),
      flag = 0,
      flag2 = 0,
      lastI = 100,
      myWindow = $(window);

// change navbar active link while scrolling
      if (flag === 0 && mainSectionLength) {
          flag = 1;
          flag2 = 0;
          for (let i = mainSectionLength - 1; i >= 0; i--) {
              if (myWindow.scrollTop() >= mainSection.eq(i).offset().top-81) {
                  if (i != lastI) {
                      links.eq(i + 1).addClass('active').siblings().removeClass('active');
                      lastI = i;
                  }
                  flag2 = 1;
                  break;
              }
          }
          if (flag2 === 0) {
              links.eq(0).addClass('active').siblings().removeClass('active');
              lastI = -1;
          }
          flag = 0;
      }
    });
  });
</script>

app/views/home/product_detail.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "slick" %>
  <%= stylesheet_link_tag  "slick", "slick-theme", "lunar" %>
<% end %>

<section id="product-detail" class="product-detail">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 p_detail">
        <div class="row justify-content-center">
          <div class="col-12 col-md-1 p_image_nav">
            <div class="product-d-nav">
              <% @images.each do |image| %>
                <div class="item"><%= image_tag image.image.url(:thumb), class: "img-fluid" %></div>
              <% end %>

            </div>
          </div>
          <div class="col-12 col-md-6 p_image">
            <div class="product-d-img">
              <% @images.each do |image| %>
                <div class="item"><%= image_tag image.image.url(:medium), class: "img-fluid" %></div>
              <% end %>
            </div>
          </div>
          <div class="col-12 p_image_mobile">
            <div class="product-d-img-mobile">
              <% @images.each do |image| %>
                <div class="item"><%= image_tag image.image.url(:medium), class: "img-fluid" %></div>
              <% end %>
            </div>
          </div>
          <div class="col-12 col-md-5 p_desc">
            <div class="cat_name"><%= @product.category_name %></div>
            <div class="p_name"><%= @product.name %></div>
            <div class="price">
              <%= number_to_currency(@product.price, unit: 'Rp ', separator: ',', delimiter: '.') %>
            </div>
            <hr />
            <div class="p_spec" style="position: relative;">
              <ul>
                <% @product.short_description.split("\n").each do |desc| %>
                  <li><%= raw desc %></li>
                <% end %>
              </ul>
              <% if @product.category_name == "Kompor Induksi" %>
                <%= image_tag "garansi.png", class: "img-fluid garansi" %>
              <% end %>
            </div>
            <div class="p_compatibility mb-4" style=" padding-left: 25px;">
              <% @product.compatibility.each do |c| %>
                <% unless c.blank? %>
                  <% style = ["panci 68", "panci k655 k625", "wajan 68"].include?(c.downcase) ? "width: 100px" : "width: 65px" %>
                  <%= image_tag "#{c.downcase.parameterize}.png", class: "img-fluid", style: "#{style}" %>
                <% end %>
              <% end %>
            </div>
            <%= link_to "Beli Sekarang", kompor_induksi_path, class: "btn btn-outline-green",
                        data: {toggle: "modal", target: "#shop_modal"} %>
          </div>
        </div>
      </div>
      <div class="col-12 col-md-12 p_icon">
        <div class="row">
          <% @feature_details.each_with_index do |detail, x| %>
            <% temp_class = (x % 2) == 0 ? "border_odd" : "border_even" %>
            <% temp_class = "" if (x + 1) == @feature_details.size %>
            <div class="col-6 col-md-3 <%= temp_class %>">
              <div class="p_icon_title"><%= detail.icon_title %></div>
              <%= link_to (image_tag detail.icon.url(:thumb), class: "img-fluid"), "##{detail.icon_title.parameterize}" %>
            </div>
          <% end %>
        </div>
      </div>

      <% @feature_details.each_with_index do |detail, x| %>
        <% temp_class_image = (x % 2) == 0 ? "order-md-1 order-1" : "order-md-2 order-1" %>
        <% temp_class_detail = (x % 2) == 0 ? "order-md-2 order-1" : "order-md-1 order-2" %>
        <div class="col-12 p_feature_detail" id="<%= "#{detail.icon_title.parameterize}" %>">
          <div class="row">
            <div class="col-12 col-md-5 <%= temp_class_image %>"><%= image_tag detail.image.url, class: "img-fluid" %></div>
            <div class="col-12 col-md-7 my-auto <%= temp_class_detail %>">
              <div class="p_feature_detail_title"><%= detail.title %></div>
              <div class="p_feature_detail_desc"><%= raw(detail.description) %></div>
            </div>
          </div>
        </div>
      <% end %>

      <% if !@product.specification.blank? || !@product.feature.blank? %>
        <div class="col-12 p_spec_feature mb-4">
          <div class="row">
            <% unless @product.specification.blank? %>
              <div class="col-12 col-md-6 spec_detail">
                <div class="row">
                  <div class="col-12"><h2>Spesifikasi</h2></div>
                  <% @product.specification.split("#").each do |spec| %>
                    <div class="col-6 detail"><%= simple_format spec %></div>
                  <% end %>
                </div>
              </div>
            <% end %>
            <% unless @product.feature.blank? %>
              <div class="col-12 col-md-6 feature_detail">
                <div class="row">
                  <div class="col-12"><h2>Fitur</h2></div>
                  <% @product.feature.split("#").each do |spec| %>
                    <div class="col-6 detail"><%= simple_format spec %></div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class="col-12 text-center">
        <%= link_to "<< Back ", root_path %>
      </div>

    </div>
  </div>
</section>

<%= render partial: "modal"  %>

<script>
  $(document).ready(function () {
    $('.product-d-img-mobile').slick({
      dots: true,
      infinite: true,
      speed: 500,
      slidesToShow: 1,
      slidesToScroll: 1,
      fade: true
    });
    
    $('.product-d-img').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      fade: true,
      asNavFor: '.product-d-nav'
    });
    $('.product-d-nav').slick({
      slidesToShow: 4,
      slidesToScroll: 1,
      asNavFor: '.product-d-img',
      vertical: true,
      focusOnSelect: true,
      arrows: false
    });
  });
</script>