config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  
  get "new-home" => "new_home#index"
  get "about_us" => "about_us#index"
  get "clients" => "clients#index"
  get "products/:permalink" => "products#index", :as => "products"
  get "products/:name/:permalink" => "products#show", :as => "product"
  get "contact_us" => "contact_us#new", :as => "contact_us"
  # post "contact_us" => "contact_us#create", :as => "contact_us"
  get "news" => "news#index", :as => "news"
  get "news/:id" => "news#show", :as => "show_news"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  resources :sessions, :only => [:create]


  get 'tentang-kompor-induksi' => 'home#kompor_induksi', as: "kompor_induksi"
  post "contact_us" => "home#contact_us", as: "save_contact_us"

  get "admin" => "admin/dashboard#index", :as => "admin"
  post "admin/dashboard/change_password"

 namespace :admin do
    resources :banners
    resources :clients
    resources :features
    resources :news, :only => [:index, :new, :create, :edit, :update, :destroy]
    resources :products do
      resources :product_images, :only => [:create, :edit, :update, :destroy] do
        member do
          get 'set_primary'
          get 'set_best_seller'
        end
      end
    end
    resources :categories
    resources :product_images, :only => [:index]
    get "product_images/:id/new_product" => "product_images#new_product", :as => "product_images_new_product"
    post "product_images/:id/create_product" => "product_images#create_product", :as => "product_images_create_product"
    get "settings/:name/edit" => "settings#edit", :as => "edit_setting"
    put "settings/:name" => "settings#update", :as => "update_setting"

    
  end

  root :to => 'home#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  # attr_accessible :name, :description, :price, :code, :permalink, :category_id, :product_images_attributes,
  #                 :image
  has_permalink :name, :update => true

  has_many :categories_products
  has_many :categories, :through => :categories_products

  has_many :product_images, :dependent => :destroy
  accepts_nested_attributes_for :product_images, :allow_destroy => true

  has_attached_file :image, :url => "/system/:attachment/:id/:style/:basename.:extension", 
                            :styles => { :thumb => "125x125",
                                         :medium => "300x300",
                                         :large => "600x600" }
  validates_attachment_presence :image
  validates :name, :presence => true,
                   :length => {:minimum => 1, :maximum => 254}
#  validates :price, :presence => true,
#                    :length => {:minimum => 1, :maximum => 254},
#                    :numericality => true

  def primary_image(size)
    img = product_images.primary.first
    return "undefined" if img.nil?
    img.product_image.url(size.to_sym)
  end

  def unset_primary
    product_images.each do |image|
      if image.is_primary?
        image.is_primary = false
        image.save!
      end
    end
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::ApplicationController
  before_filter :find_product, :only => [:show, :destroy, :edit, :update]

  def index
    @products = Product.paginate(:page => params[:page], :per_page => 20,
                                         :order => "created_at DESC" )
    @no = params[:page].to_i * 20
  end

  def new
    @product = Product.new
    @product.product_images.build
    @category_list = Category.category_list
    @product_category = []
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      update_categories
      flash[:notice] = "Product successfully created"
      redirect_to admin_products_path
    else
      @category_list = Category.category_list
      @product_category = params[:product][:category_id].map(&:to_i)
      flash[:error] = "Product failed to create"
      render :action => "new"
    end
  end

  def show
    @product_image = ProductImage.new
    @product_images = @product.product_images
  end

  def edit
    @product_category = @product.categories.map(&:id)
  end

  def update
    puts params.inspect
    if @product.update_attributes(params[:product])
      update_categories
      flash[:notice] = "Product successfully updated"
      redirect_to admin_products_path
    else
      @product_category = @product.categories.map(&:id)
      flash[:error] = "Product failed to update"
      render :action => "edit"
    end
  end

  def destroy
    flash[:notice] =  @product.destroy ? 'Product was successfully deleted.' :
                                      'Product was falied to delete.'
    redirect_to admin_products_path
  end

  private
    def find_product
      @product = Product.find_by_id(params[:id])
      if @product.nil?
        flash[:error] = "Cannot find the Product with id '#{params[:id]}'"
        redirect_to admin_products_path
      end
    end

    def update_categories
      @categories = Category.where("id in (?)", params[:product][:category_id])
      @product.categories = @categories
      @product.save
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_category, :only => [:index]
  before_action :find_product, :only => [:show]

  def index
    if @category.parent_id.nil?
      @parent_category = @category
      @child_categories = @parent_category.child_categories
      @products = Product.joins("left join categories_products as cp on cp.product_id = products.id").
                          where("cp.category_id in (?)", @child_categories.map(&:id)).distinct
    else
      @parent_category = @category.parent_category
      @child_categories = @parent_category.child_categories
      @products = @category.products
    end

    params[:page] = params[:page] || 1
    params[:per] = params[:per] || 15
    @products = @products.page(params[:page]).per(params[:per])
  end

  def show
    @product_images = @product.product_images
  end

  private
    def find_category
      @category = Category.includes(:products).find_by_permalink(params[:permalink])
      if @category.nil?
        flash[:error] = "Cannot find the category"
        redirect_to root_path
      end
    end

    def find_product
      @product = Product.find_by_permalink(params[:permalink])
      if @product.nil?
        flash[:error] = "Cannot find the Product"
        redirect_to root_path
      end
    end
end

app/views/admin/products/_form.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "/assets/ckeditor/ckeditor" %>
<% end %>

<div class="field">
  <div class="input-title left"><%= f.label :name, "Name * :" %></div>
  <div class="input-box left"><%= f.text_field :name %></div>
</div>
<div class="field clear-margin">
  <div class="input-title left"><%= f.label :price, "Price :" %></div>
  <div class="input-box left"><%= f.text_field :price %></div>
</div>
<div class="field clear-margin">
  <div class="input-title left"><%= f.label :code, "Code :" %></div>
  <div class="input-box left"><%= f.text_field :code %></div>
</div>
<div class="field clear-margin" style="margin-bottom:0px">
  <div class="input-title left"><%= f.label :image, "Image * :" %></div>
  <div class="input-box left"><%= f.file_field :image %></div>
</div>
<div class="field clear-margin">
  <div class="input-title left">&nbsp;</div>
  <div class="input-box left small-font">
    Input image with size 800x600 (width x height)
  </div>
</div>
<!--
<%# unless params[:action] == "edit" %>
  <%#= f.fields_for :product_images do |pi| %>
    <%#= pi.hidden_field :is_primary, :value => true %>
    <%#*<div class="field clear-margin">%>
      <%#*<div class="input-title left"><%= pi.label :product_image, "Primary Image * :" %></div>%>
      <%#*<div class="input-box left"><%= pi.file_field :product_image %></div>%>
    <%#*</div>%>
    <%#*<div class="field clear-margin">%>
      <%#*<div class="input-title left">&nbsp;</div>%>
      <%#*<div class="input-box left small-font">%>
        <%#*Input image with size 400x300 (width x height)%>
      <%#*</div>%>
    <%#*</div>%>
  <%# end %>
<%# end %>-->
<div class="field clear-margin" style="width:900px;height:auto;">
  <div class="input-title left"><%= f.label :category_id, "Category * :" %></div>
  <div class="input-box left" style="width:700px;">
    <div class="input-box left" style="width:700px;">
          <% Category.parent_categories.each_with_index do |parent_cat, i| %>
            <%# style = "" %>
            <% if i == 0 %>
              <% style = "padding-right: 20px;border-right: 1px solid #000" %>
            <% else %>
              <% style = "padding-left: 20px;" %>
            <% end %>
            <div style="width:325px;float: left;<%= style %> ">
              <div style="margin-bottom:15px"><%= parent_cat.name.titleize %> : </div>
              <% parent_cat.child_categories.each do |cat| %>
                <div style="margin-bottom:5px">
                  <%= check_box_tag "product[category_id][]", cat.id, @product_category.include?(cat.id) %>&nbsp;
                  <%= cat.name %>&nbsp;&nbsp;&nbsp;
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
    <%# Category.child_categories.each do |cat| %>
      <%#= check_box_tag "product[category_id][]", cat.id, @product_category.include?(cat.id) %>&nbsp;
      <%#= cat.name %>&nbsp;&nbsp;&nbsp;
    <%# end %>
    <%#= f.select :category_id, Category.child_categories.collect {|p| [ p.name, p.id ] } %>
    <%#*<div class="category_list">%>
      <%#*pencil%>
    <%#*</div>%>
    <%#*<div class="category_list">%>
      <%#*Embroidery%>
    <%#*</div>%>
  </div>
</div>
<div class="field">
  <div class="input-title left"><%= f.label :description, "Description :" %></div>
  <div class="input-box left">&nbsp;</div>
</div>
<div class="field" style="height: 440px;">
  <%= f.cktext_area :description,
                    :ckeditor => {:uiColor => "#F5CDFA", :toolbar => "Basic",
                                  :width=>'850px', :height=>'250px'}  %>
</div>

app/views/admin/products/edit.html.erb
<div class="admin-inner-content">
  <div class="admin-inner-content-title">Edit Product</div>
  <div class="admin-inner-content-info">
    <%= raw msg_flash(flash) %>
    <%= form_for([:admin, @product],
                  :html => { :multipart => true, :method => :put }) do |f| %>
      <%= f.error_messages %>
      <div style="height: 225px;">
        <%#= image_tag @product.primary_image("medium") %>
        <%= image_tag @product.image.url("medium") %>
      </div><br /><br />
      <%= render :partial => 'form', :locals => { :f => f} %>
      <div class="field">
        <%= f.submit 'Update Product' %>&nbsp;&nbsp;
        <%= link_to 'Back', admin_products_path %>
      </div>
    <% end %>
    <div class="clear"></div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="admin-inner-content">
  <div class="admin-inner-content-title">Products</div>
  <div class="admin-inner-content-info">
    <%= raw msg_flash(flash) %>
    <%= link_to "Add New Product", new_admin_product_path %><br /><br />
    <div class="admin-row border">
      <div class="no">No</div>
      <div class="product-image">Image</div>
      <div class="product-name">Name</div>
      <div class="product-price">Price</div>
      <div class="product-category">Category</div>
      <div class="product-action">&nbsp;</div>
    </div>
    <% @products.each_with_index do |product, x| %>
      <div class="admin-row with-pic">
        <div class="no"><%= x+1 %></div>
        <div class="product-image">
          <%#= image_tag product.primary_image("thumb") %>
          <%= image_tag product.image.url("thumb") %>
        </div>
        <div class="product-name"><%= product.name %></div>
        <div class="product-price">
          <%= number_to_currency(product.price, :unit => "Rp. ", :separator => ",") %>
        </div>
        <div class="product-category"><%= product.categories.map(&:name).join(", ") %></div>
        <div class="product-action">
          <%#= link_to 'Add Image', admin_product_path(product.id) %><%#*&nbsp;|&nbsp;%>
          <%= link_to 'Edit', edit_admin_product_path(product.id) %>&nbsp;|&nbsp;
          <%= link_to 'Delete', admin_product_path(product.id),
                                :confirm => "Are you sure?", :method => :delete %>
        </div>
      </div>
    <% end %>
    <div class="paginate"><%= will_paginate @products, :link_separator => " | ",
                                 :previous_label => "&laquo; previous",
                                 :next_label => "next &raquo;" %></div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="admin-inner-content">
  <div class="admin-inner-content-title">Product</div>
  <div class="admin-inner-content-info">
    <%= raw msg_flash(flash) %>
    <%= form_for([:admin, @product],
                  :html => { :multipart => true}) do |f| %>
      <%= f.error_messages %>
      <%= render :partial => 'form', :locals => { :f => f} %>
      <div class="field">
        <%= f.submit 'Create Product' %>&nbsp;&nbsp;
        <%= link_to 'Back', admin_products_path %>
      </div>
    <% end %>
    <div class="clear"></div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="admin-inner-content">
  <div class="admin-inner-content-title">New Product Images</div>
  <div class="admin-inner-content-info">
    <%= form_for([:admin, @product], 
                  :url => admin_product_product_images_path(@product.id),
                  :html => { :multipart => true, :method => :post}) do |f| %>
      <%= f.error_messages %>
      <div class="field clear-margin">
        <div class="input-title left"><%= f.label :product_image, "Image * :" %></div>
        <div class="input-box left"><%= f.file_field :product_image %></div>
      </div>
      <div class="field clear-margin">
        <div class="input-title left">&nbsp;</div>
        <div class="input-box left small-font">
          Input image with size 800x600 (width x height)
        </div>
      </div>
      <div class="field">
        <%= f.submit 'Create Product Image' %>&nbsp;&nbsp;
        <%= link_to 'Back', admin_products_path %>
      </div>
    <% end %>
    <div class="admin-product-images-title">
      Product Images
    </div>
    <% @product_images.each_with_index do |product_image, x| %>
      <div class="admin-product-images">
        <div class="pic">
          <%= image_tag product_image.product_image.url(:medium) %>
        </div>
        <div class="action">
          <span><%= product_image.is_primary? ? "Is Primary" :
              (link_to "Set as Primary", set_primary_admin_product_product_image_path(
                        :product_id => @product.id, :id => product_image.id)) %></span>|
          <span><%= link_to "Edit", edit_admin_product_product_image_path(
                                :product_id => @product.id, 
                                :id => product_image.id ) %></span>|
          <span><%= link_to "Delete", admin_product_product_image_path(
                                :product_id => @product.id, :id => product_image.id ),
                                :confirm => "Are you sure?", :method => :delete %></span>
           <span class="best-seller">
            <%= check_box_tag "is_best_seller", true, product_image.is_best_seller,
                {:id => "best_#{x+1}", :onclick => "is_best_seller_picture('best_#{x+1}',
                                                                         '#{@product.id}',
                                                                         '#{product_image.id}');"} %>
             <span>best seller</span>
             <span><%= image_tag "bx_loader.gif", :size => "15x15",
                                 :id => "loader_best_#{x+1}", :style => "display:none" %></span>
           </span>
        </div>
      </div>
    <% end %>
    <div class="clear"></div>
  </div>
</div>